#!/usr/bin/env ksh

# variables

# BSD ls(1) cares about this, GNU ls(1) does not
export CLICOLOR=1

CDPATH=.:~:~/src:~/Google\ Drive/Documents/Continuing\ Education
FIGNORE='@(*.o|~*)'

# force OSTYPE to always be lower case
typeset -l OSTYPE=$(uname)

# colors

BLACK=$(printf '\033[0;30m')
RED=$(printf '\033[0;31m')
GREEN=$(printf '\033[0;32m')
YELLOW=$(printf '\033[0;33m')
BLUE=$(printf '\033[0;34m')
PURPLE=$(printf '\033[0;35m')
CYAN=$(printf '\033[0;36m')
WHITE=$(printf '\033[0;37m')
OFF=$(printf '\033[0m')

# xterm titlebar

TITLEBAR=$(printf '\033]0;')
BELL=$(printf '\007')

# I don't like the default macOS sudo password prompt, so change it.
# wrap it so it only affects macOS

[[ "$OSTYPE" == "darwin" ]] && export SUDO_PROMPT='[sudo] password for %p:'

# disable MS telemetry for mssql-cli tool
export MSSQL_CLI_TELEMETRY_OPTOUT=1

# define a cheat so I can get to my play linode nanos
BOUNCER=173.230.149.72
DEBIAN=50.116.2.62
