#!/usr/bin/env ksh

# variables

CDPATH=.:~:~/src:~/Google\ Drive/Documents/Continuing\ Education
FIGNORE='@(*.o|~*)'

# force OSTYPE to always be lower case
typeset -l OSTYPE=$(uname)

# colors

BLACK=$(printf '\033[0;30m')
RED=$(printf '\033[0;31m')
GREEN=$(printf '\033[0;32m')
YELLOW=$(printf '\033[0;33m')
BLUE=$(printf '\033[0;34m')
PURPLE=$(printf '\033[0;35m')
CYAN=$(printf '\033[0;36m')
WHITE=$(printf '\033[0;37m')
OFF=$(printf '\033[0m')

# BSD ls(1) cares about this, GNU ls(1) does not
CLICOLOR=1

# xterm titlebar

TITLEBAR=$(printf '\033]0;')
BELL=$(printf '\007')
