#!/usr/bin/env ksh

# proctools

function pkill {
    typeset pid
    pid=$(ps ax | grep $1 | grep -v grep | awk '{ print $1 }')
    kill -9 $pid
    printf "Killed $1 (process $pid)\n"
}

function pgrep {
    ps aux | grep $1 | grep -v grep
}

